# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

global_vars:
  - name: current_date
    type: date
    params:
      format: "%Y-%m-%d" # YYYY-MM-DD
  - name: current_time
    type: date
    params:
      format: "%H:%M:%S" # HH:MM:SS
  - name: full_datetime
    type: date
    params:
      format: "%Y-%m-%d %H:%M:%S" # YYYY-MM-DD HH:MM:SS
  - name: tomorrow_date
    type: date
    params:
      format: "%x" # System's localized date format
      offset: 86400 # 24 hours in seconds for tomorrow
  - name: yesterday_date
    type: date
    params:
      format: "%x"
      offset: -86400 # 24 hours in seconds for yesterday

matches:
  # Simple text replacement
  - trigger: ".espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ".date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ".shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
  
  # em dash
  - trigger: ".emdash"
    replace: "—"

  # My note signature
  - trigger: ".nnjsig"
    replace: "Newlyn Joseph, M.D., M.S.\nPGY3 Psychiatry\nAlbany Medical Center\nSigned {{full_datetime}}"

  # My email signature
  - trigger: ".nnjesig"
    replace: |
      Newlyn Joseph, M.D., M.S.
      Albany Medical Center, Department of Psychiatry
      josephn4@amc.edu
      new.joseph10@gmail.com | newlyn.joseph@aya.yale.edu
      Cell: (203) 584-6402 | Fax: (661) 220-7524

  # Dictation disclaimer
  - trigger: ".nnjdictation"
    replace: "This note was generated using Dragon Medical One, errors may be present in transcription."

  # delirium recs
  - trigger: ".nnjdelirium"
    replace: |
      — Avoid or minimize all potentially deliriogenic medications where possible, especially anticholinergics and benzodiazepines, and use the minimum effective dose of short-acting agents where needed.  
      — Follow labs and vitals closely, frequent Urinalysis.  
      — Maintain a low threshold to repeat neuroimaging, especially if patient falls, has an abrupt change in mentation, or new focal findings in the setting of impaired examination (although low yield).  
      — We recommend the following behavioral Interventions:
        1. Lights on with shades open during the day.
        2. Frequent re-orientation.
        3. Visible analog clock and calendar.
        4. Appropriate simulation levels.
        5. Encourage use of sensory aids.
        6. Mobilize or ambulate with assistance as soon as possible.
        7. Sleep protection (but use no hypnotics of any kind).
        8. Avoid restraints if possible. Please consider low bed with mats, mittens or a patient companion first.

  # phq9 form
  - trigger: ".nnjphq9"
    form: |
      Patient Health Questionnaire-9 (PHQ-9)
      Over the last 2 weeks, how often have you been bothered by any of the following problems?
      
      Little interest or pleasure in doing things
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Feeling down, depressed, or hopeless
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Trouble falling or staying asleep, or sleeping too much
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Feeling tired or having little energy
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Poor appetite or overeating
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Feeling bad about yourself — or that you are a failure or have let yourself or your family down
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Trouble concentrating on things, such as reading the newspaper or watching television
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      Thoughts that you would be better off dead, or thoughts of hurting yourself in some way
      [ ] Not at all (0)
      [ ] Several days (1)
      [ ] More than half the days (2)
      [ ] Nearly every day (3)
      
      If you checked off any problems, how difficult have these problems made it for you to do your work, take care of things at home, or get along with other people?
      [ ] Not difficult at all
      [ ] Somewhat difficult
      [ ] Very difficult
      [ ] Extremely difficult
      
      Add up the scores for each of the 9 questions.
      Total score: ***
      
      Interpretation of scores:
      0-4: Minimal depression
      5-9: Mild depression
      10-14: Moderate depression
      15-19: Moderately severe depression
      20-27: Severe depression

  # student note disclaimer
  - trigger: ".nnjstudentnote"
    replace: "THIS IS A MEDICAL STUDENT NOTE, PLEASE SEE RESIDENT NOTE FOR PLAN OF CARE."

  # mental status exam
  - trigger: ".nnjmse"
    form: |
      MSE:   
      Appearance: Patient appears their stated age. [[gender]] is seated comfortably in chair during encounter. [[gender]] is not disheveled. 
      Behavior/attitude: Patient maintains good eye contact throughout interview
      Psychomotor: No involuntary movements. No noted tics or tremors. 
      Speech: Speech is fluent without aphasia or dysarthria. Normal rate and rhythm. No pressured speech. Volume is unremarkable.  
      Mood: Stated mood is "[[mood]]"  
      Affect: Euthymic, normal range of affect, with no affect lability. There were no episodes of tearfulness or irritability during interview. 
      Thought Process: Linear, logical, and organized. No tangentiality, No circumstantiality. Does not require constant redirection to answer questions. Does not display any flight-of-ideas.  
      Thought Content: Significant religious and persecutory delusions. Significant paranoid thinking pertaining to hospitals and mental health institutions. Denies experiencing passive death wish or active suicidal ideation during the encounter. Denies homicidal ideation.  
      Perception: Denied any AVH. Evidence of reacting to internal stimuli when observed on the unit.  
      Cognition/memory/attention: Awake, alert, and oriented x3. Memory grossly intact. Attention grossly intact.  
      Insight: {GOOD/FAIR/POOR/EXCELLENT:24238}
      Judgment: {GOOD/FAIR/POOR/EXCELLENT:24238}
      Impulsivity: Intact over the course of the examination   
    form_fields:
      mood:
        type: text
      gender:
        type: choice
        values:
          - He
          - She
          - They
  
  # dispo statement for an in
  - trigger: ".nnjdispoin"
    replace: "Currently, patient presents with elevated imminent risk of harm to self and would benefit from further psychiatric care in the least restrictive setting consistent with their degree of psychiatric impairment, which presently is in the inpatient setting for the purpose of acute stabilization medication initiation/optimization, and brief respite."
    
  # dispo statement for an out
  - trigger: ".nnjdispoout"
    replace: "Currently, patient does not present with elevated imminent risk of harm to self and would benefit from further psychiatric care in the least restrictive setting consistent with their degree of psychiatric impairment, which would be outpatient."
  
  # psych ROS
  - trigger: ".nnjros"
    replace: |
      Psychiatric Review Of Systems:
      sleep: none
      appetite changes: none
      weight changes: none
      energy/anergy: none
      interest/pleasure/anhedonia: none
      somatic symptoms: none
      libido: none
      anxiety/panic: none
      guilty/hopeless: none
      S.I.B.s/risky behavior: none
      any drugs: none
      alcohol: none
  
  # risk assessment block
  - trigger: ".nnjrisk"
    form: |
      Overall Risk Assessment:
      Suicide: Appears [[scale]]. Fixed risk factors include {amkriskfactorsforsuicide:29240}. Modifiable risk factors include {amkriskfactorsforsuicide-mod:32178}. Protective factors include {amkprotectivefactorsforsuicide:29244}.
      Self-injury: Appears [[scale]]. Patient {amkdo:28993} have history of prior self-injurious behavior, including *** 
      Dangerousness to Others: Appears [[scale]]. {AMKviolence:29257}
    form_fields:
      scale:
          type: choice
          values:
            - low
            - moderate
            - high

  # attending staffing block
  - trigger: ".nnjstaff"
    form: |
      Patient [[discussion_status]] with psychiatry attending, Dr. [[attending]]. Thank you for the consult.
    form_fields:
      discussion_status:
        type: choice
        values:
          - discussed
          - to be discussed
      attending:
        type: text

  - trigger: ".nnjblackbox"
    replace: "When prescribing psychotropics for elderly patients, it is important to be aware of the black box warning associated with certain medications, particularly antipsychotics. These medications carry an increased risk of mortality in elderly patients with dementia-related psychosis. The warning highlights the potential for cardiovascular events, such as heart failure and sudden death, as well as infectious events like pneumonia. Therefore, careful consideration and monitoring are essential when using these medications in the elderly, weighing the potential benefits against the risks. Always start with the lowest effective dose, titrate slowly, and regularly reassess the need for continued use."

  - trigger: ".nnjaims"
    form: |
      AIMS Exam: Abnormal Involuntary Movement Scale

      I. Facial and Oral Movements
      [ ] 0 - None
      [ ] 1 - Minimal (may be extreme normal)
      [ ] 2 - Mild
      [ ] 3 - Moderate
      [ ] 4 - Severe

      Lips and Perioral Area: Puckering, pouting, smacking, chewing, sucking, grimacing
      Observed: [ ]

      Jaw: Clenching, wide opening, lateral movements
      Observed: [ ]

      Tongue: Protrusion, retractions, side-to-side movements
      Observed: [ ]

      II. Extremity Movements
      [ ] 0 - None
      [ ] 1 - Minimal (may be extreme normal)
      [ ] 2 - Mild
      [ ] 3 - Moderate
      [ ] 4 - Severe

      Upper Extremities (Arms, Wrists, Hands, Fingers): Choreiform (rapid, jerky), athetoid (slow, writhing), pill-rolling, tics, tremors
      Right: [ ]
      Left: [ ]

      Lower Extremities (Legs, Ankles, Feet, Toes): Rocking, stomping, walking in place, kicking, foot tapping, toe movements
      Right: [ ]
      Left: [ ]

      III. Trunk Movements
      [ ] 0 - None
      [ ] 1 - Minimal (may be extreme normal)
      [ ] 2 - Mild
      [ ] 3 - Moderate
      [ ] 4 - Severe

      Neck, Shoulders, Hips: Rocking, twisting, squirming, forward/backward movements
      Observed: [ ]

      IV. Global Severity and Incapacitation
      Overall Severity of Abnormal Movements:
      [ ] 0 - None
      [ ] 1 - Minimal
      [ ] 2 - Mild
      [ ] 3 - Moderate
      [ ] 4 - Severe

      Incapacitation Due to Movements: (How much do movements interfere with daily activities?)
      [ ] 0 - None
      [ ] 1 - Minimal (no interference)
      [ ] 2 - Mild (slight interference, patient can compensate)
      [ ] 3 - Moderate (significant interference, patient has difficulty)
      [ ] 4 - Severe (movements incapacitating, patient cannot function independently)

      V. Dental Status (Check all that apply)
      [ ] 1. No teeth
      [ ] 2. Dentures
      [ ] 3. Partial plates
      [ ] 4. All/most teeth present

      Additional Observations/Comments:

  - trigger: ".nnjhunter"
    form: |
      Hunter Serotonin Toxicity Criteria Form

      Serotonergic Agent Exposure: [ ] Yes [ ] No
      Spontaneous Clonus: [ ] Yes [ ] No
      Inducible Clonus + Agitation or Diaphoresis: [ ] Yes [ ] No
      Ocular Clonus + Agitation or Diaphoresis: [ ] Yes [ ] No
      Tremor and Hyperreflexia: [ ] Yes [ ] No
      Hypertonia and Temperature >38°C (100.4 F) + Ocular or Inducible Clonus: [ ] Yes [ ] No

      Diagnosis of serotonin syndrome is made if serotonergic agent exposure is present and any one of the above criteria is met.
  
  # And much more! For more information, visit the docs: https://espanso.org/docs/
